import React,{useMemo,useState} from 'react';
import cards,{curriculumMeta} from './data/curriculum';
import training90 from './data/training90';
import {loadProgress,saveProgress,recordAttempt,advanceCard,setDay,checkpoint,resetProgress} from './engine/progress';
import {testCard,gradeCheckpoint} from './engine/testing';
import {gradeResponse,MASTERY} from './engine/grading';
import {nextReview,recoveryState} from './engine/review';

function App(){
 const [progress,setProgress]=useState(loadProgress); const [view,setView]=useState('dashboard'); const [phase,setPhase]=useState('study'); const [answer,setAnswer]=useState(''); const [result,setResult]=useState(null); const [scenario,setScenario]=useState(''); const [scenarioResult,setScenarioResult]=useState(null);
 const card=cards.find(c=>c.id===progress.currentCard)||cards[cards.length-1];
 const mastered=Object.values(progress.mastered).filter(Boolean).length;
 const currentCheckpoint=curriculumMeta.checkpoints.find(n=>n===mastered+1)||null;
 const persist=p=>{setProgress(p);saveProgress(p)};
 const submitTest=()=>{const r=testCard(card,answer);setResult(r);if(!r.passed){persist(recordAttempt(progress,card,r));setPhase('review');}else setPhase('scenario')};
 const submitScenario=()=>{const r=gradeResponse({...card,test:{...card.test,required:[card.answer,...card.test.required]}},scenario);setScenarioResult(r);if(r.passed){const p=recordAttempt(progress,{...r,score:Math.min(result?.score??100,r.score)});persist(advanceCard(p,cards.length));setAnswer('');setScenario('');setResult(null);setScenarioResult(null);setPhase('study')}else{const p=recordAttempt(progress,r);persist(p);setPhase('review')}};
 const retry=()=>{setAnswer('');setScenario('');setResult(null);setScenarioResult(null);setPhase('study')};
 const useReview=()=>{const r=nextReview(cards,progress);if(r){persist({...progress,currentCard:r.id});setView('study');retry()}};
 const check= n=>{const r=gradeCheckpoint(cards.slice(0,n),progress);persist(checkpoint(progress,n,r.passed));return r};
 return <div className="app">
  <header><div><div className="eyebrow">FOGLE UNLIMITED</div><h1>Technology Entrepreneur Academy</h1><p className="sub">Instructor-led. Flashcard-first. Strict mastery.</p></div><button className="ghost" onClick={()=>setView('dashboard')}>Dashboard</button></header>
  <nav>{[['dashboard','Academy'],['study','Flashcards'],['daily','90-Day'],['checkpoints','Checkpoints']].map(([id,label])=><button className={view===id?'active':''} onClick={()=>setView(id)} key={id}>{label}</button>)}</nav>
  {view==='dashboard'&&<Dashboard mastered={mastered} progress={progress} setView={setView} useReview={useReview}/>} 
  {view==='study'&&<Study card={card} phase={phase} setPhase={setPhase} answer={answer} setAnswer={setAnswer} result={result} submitTest={submitTest} scenario={scenario} setScenario={setScenario} scenarioResult={scenarioResult} submitScenario={submitScenario} retry={retry} progress={progress}/>} 
  {view==='daily'&&<Daily progress={progress} persist={persist}/>} 
  {view==='checkpoints'&&<Checkpoints progress={progress} check={check}/>} 
 </div>
}
function Dashboard({mastered,progress,setView,useReview}){const pct=Math.round(mastered/200*100);const failed=Object.values(progress.failed).filter(Boolean).length;return <main className="stack"><section className="heroCard"><div><span className="pill">ACTIVE LEVEL</span><h2>{mastered<80?'Basic':mastered<160?'Intermediate':'Advanced'}</h2><p>Study → Memorize → Practice → Recall → Test → Apply → Repeat → Advance</p></div><div className="bigStat">{pct}%</div></section><section className="grid"><Stat label="Mastered" value={`${mastered}/200`}/><Stat label="Failed areas" value={failed}/><Stat label="Training day" value={`${progress.trainingDay}/90`}/><Stat label="Next card" value={progress.currentCard}/></section><section className="panel"><h3>Instructor directive</h3><p>Today, study the supplied material. Do not invent the curriculum. Your job is to retrieve it, apply it, and prove mastery at {MASTERY}% or higher.</p><div className="actions"><button onClick={()=>setView('study')}>Start current card</button>{failed>0&&<button className="secondary" onClick={useReview}>Review a failed card</button>}</div></section><section className="panel"><h3>Fogle Unlimited anchor</h3><p><b>Mr. Fogle:</b> Independent Technology Entrepreneur.</p><p><b>Company:</b> Fogle Unlimited.</p><p>Fogle Unlimited builds practical businesses, services, and technology systems that solve real problems for people and organizations.</p><p className="note">The “$80 Million Man” is an internal long-term identity target, not a present financial claim.</p></section></main>}
function Stat({label,value}){return <div className="stat"><span>{label}</span><strong>{value}</strong></div>}
function Study({card,phase,setPhase,answer,setAnswer,result,submitTest,scenario,setScenario,scenarioResult,submitScenario,retry,progress}){const rec=recoveryState(progress,card.id);return <main className="studyWrap"><div className="progressLine"><span>Card {card.id} / 200</span><span>{card.level} · {card.area}</span></div><section className="flashcard"><span className="pill">STUDY</span><h2>{card.front}</h2>{phase==='study'&&<button onClick={()=>setPhase('test')}>Flip / reveal lesson</button>}{phase!=='study'&&<div className="lesson"><h3>Training material</h3><p>{card.back}</p><p><b>Practice phrase:</b> {card.answer}</p><p><b>Common failure:</b> {card.commonMiss}</p></div>}</section>{phase==='test'&&<section className="panel"><div className="type">{card.test.type}</div><h3>Strict test</h3><p>{card.test.prompt}</p><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Recall the required material. Do not rely on filler."/><button onClick={submitTest} disabled={!answer.trim()}>Grade response</button></section>}{result&&<section className={`result ${result.passed?'pass':'fail'}`}><strong>{result.score}% — {result.passed?'PASS':'REVIEW'}</strong><p>{result.feedback}</p>{result.missing?.length>0&&<p>Missing: {result.missing.join(', ')}</p>}</section>}{phase==='scenario'&&<section className="panel"><div className="type">SIMULATION / FICTIONAL TRAINING SCENARIO</div><h3>Application test</h3><p>{card.application}</p><textarea value={scenario} onChange={e=>setScenario(e.target.value)} placeholder="Respond as Mr. Fogle. Apply the training rule."/><button onClick={submitScenario} disabled={!scenario.trim()}>Evaluate application</button></section>}{scenarioResult&&<section className={`result ${scenarioResult.passed?'pass':'fail'}`}><strong>{scenarioResult.score}% — {scenarioResult.passed?'CARD MASTERED':'RETEACH REQUIRED'}</strong><p>{scenarioResult.feedback}</p></section>}{phase==='review'&&<section className="panel recovery"><h3>{rec.active?'Recovery / reteaching activated':'Review and retry'}</h3><p>{rec.active?'Three failures reached. Re-teach the material now, then retry. The failure remains tracked.':'Below 80% is not mastered. Re-study the lesson and retry.'}</p><button onClick={retry}>Re-teach and retry</button></section>}</main>}
function Daily({progress,persist}){const d=training90[progress.trainingDay-1];return <main className="stack"><section className="panel"><div className="progressLine"><span>DAY {d.day} / 90</span><span>{d.phase}</span></div><h2>{d.behavior}</h2><Block title="Behavior of the Day" text={d.behavior}/><Block title="Verbal Practice" text={d.verbalPractice}/><Block title="Real-World Business Action" text={d.realWorldAction}/><Block title="Scenario Training" text={d.scenario}/><Block title="Memory Training" text={d.memoryTraining}/><Block title="Identity Audit" text={d.identityAudit}/><div className="actions"><button disabled={d.day===90} onClick={()=>{const p=setDay(progress,d.day+1);persist(p)}}>Mark day complete / next day</button></div></section></main>}
function Block({title,text}){return <div className="block"><h3>{title}</h3><p>{text}</p></div>}
function Checkpoints({progress,check}){const [msg,setMsg]=useState(null);return <main className="stack"><section className="panel"><h2>Cumulative checkpoints</h2><p>Each checkpoint tests cumulative retention. The standard is {MASTERY}% or higher, with no weak cards below the threshold.</p><div className="checkpointGrid">{curriculumMeta.checkpoints.map(n=>{const done=progress.checkpoints?.[n];return <div className="checkpoint" key={n}><strong>{n}</strong><span>{done===true?'PASSED':done===false?'REVIEW':'LOCKED'}</span><button disabled={Object.keys(progress.mastered).length<n} onClick={()=>setMsg({n,r:check(n)})}>Test</button></div>})}</div>{msg&&<div className={`result ${msg.r.passed?'pass':'fail'}`}><strong>Checkpoint {msg.n}: {msg.r.score}% — {msg.r.passed?'PASS':'REVIEW'}</strong>{!msg.r.passed&&<p>Return to the listed weak cards and retry before advancing.</p>}</div>}</section></main>}
export default App;
