import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";
import { identityManual, recallItems } from "./identityManual";

const KEY = "te_identity_training_v2";

const sections = [
  ["identity", "Professional Identity", ["Professional identity", "Mission", "Values", "Standards", "Strengths", "Weaknesses", "Skills"]],
  ["business", "Business Knowledge", ["Technology", "Business models", "Customers", "Problems", "Solutions", "Value", "Revenue", "Costs", "Metrics"]],
  ["communication", "Communication", ["Clear speaking", "Active listening", "Asking questions", "Explaining ideas", "Professional language", "Handling uncertainty"]],
  ["decision", "Decision Making", ["Facts", "Options", "Risks", "Tradeoffs", "Decisions", "Follow-through"]],
  ["leadership", "Leadership", ["Responsibility", "Reliability", "Communication", "Delegation", "Accountability", "Problem solving"]],
  ["sales", "Sales", ["Discovery", "Customer problems", "Value", "Objections", "Offers", "Follow-up", "Asking for the sale"]],
  ["negotiation", "Negotiation", ["Preparation", "Interests", "Options", "Boundaries", "Tradeoffs", "Agreement"]],
  ["emotion", "Emotional Control", ["Rejection", "Criticism", "Pressure", "Uncertainty", "Failure", "Difficult conversations"]],
  ["money", "Money", ["Revenue", "Expenses", "Profit", "Cash flow", "Pricing", "Saving", "Reinvestment"]],
  ["standards", "Professional Standards", ["Reliability", "Preparation", "Honesty", "Follow-through", "Professional appearance", "Professional communication", "Keeping commitments"]]
];

const lessons = {
  identity: ["A professional identity is built through truthful, repeatable behavior.", ["Use truthful facts.", "Ask before assuming.", "Practice the behavior you want to make normal."], "State your identity, mission, purpose, values, and motto from memory."],
  business: ["Entrepreneurs solve real problems for specific people.", ["Start with the customer problem.", "Know how value is created.", "Track money clearly."], "Explain the Fogle Unlimited business engine from market through delivery and growth."],
  communication: ["Clear communication reduces confusion.", ["Listen before answering.", "Use simple words.", "Say what you know and do not know."], "Deliver the 30-second Business System Setup explanation without inventing claims."],
  decision: ["Good decisions use facts, options, tradeoffs and action.", ["Separate facts from assumptions.", "Choose a next action.", "Review results."], "Explain how you would decide whether to build or sell a new solution."],
  leadership: ["Leadership is shown through responsibility and useful action.", ["Own commitments.", "Communicate early.", "Solve problems."], "Describe how you would handle a missed deadline while protecting customer trust."],
  sales: ["Sales starts with understanding a problem and matching a truthful offer.", ["Discover before pitching.", "Sell outcomes, not hype.", "Ask for the next step."], "Run a discovery-to-next-step conversation for a business with disorganized work."],
  negotiation: ["Negotiation works better when interests and boundaries are clear.", ["Prepare first.", "Know your boundary.", "Look for mutual value."], "Respond to a buyer asking for more work without increasing price."],
  emotion: ["Professional behavior includes deliberate responses under pressure.", ["Pause before reacting.", "Separate feedback from identity.", "Return to facts and objectives."], "Respond to a harsh customer complaint without becoming defensive."],
  money: ["A business must understand revenue, costs, profit and cash flow.", ["Know the numbers.", "Protect cash flow.", "Price from value and costs."], "Explain the difference between revenue, costs, profit, and cash flow."],
  standards: ["Professional reputation is built through repeated observable behavior.", ["Be on time.", "Prepare.", "Do what you said you would do."], "State the Fogle Unlimited professional standards and motto from memory."]
};

const scenarios = [
  ["Client Discovery", "A small business owner says work is disorganized and staff keep missing tasks. Act as Mr. Fogle: ask discovery questions before offering a solution."],
  ["Client Pressure", "The owner says, 'Just build me an app.' You do not yet know the real problem. Respond without jumping into a solution."],
  ["Marketing", "You need an ad for Business System Setup. Explain the problem, truthful result, audience, and next step without hype or invented proof."],
  ["Funnel", "A prospect clicked your message but says they are not ready to buy. Move them to the next appropriate step without pressure or deception."],
  ["Sales", "A prospect says, 'I already have someone.' Respond professionally, learn why, and protect the relationship."],
  ["Pricing", "A prospect says your price is too high. Ask a useful question, explain scope, and do not invent savings or results."],
  ["Negotiation", "A buyer wants extra work for the same price. State the boundary and offer a clear scope tradeoff."],
  ["Delivery", "A customer says a promised item is missing. Own the issue, explain the next step, and avoid excuses."],
  ["Technical Unknown", "A customer asks a technical question you cannot verify. Answer without pretending to know."],
  ["High Pressure", "A customer demands an unreasonable promise today. Protect the standard, explain what can be done, and propose the next step."]
];

const dailyItems = ["Identity review", "Verbal practice", "Scenario drill", "Real-world business action", "Behavior of the day", "Evening review"];
const identityRules = [
  "Ask questions before making assumptions.", "Listen completely before responding.", "Speak clearly and use simple words.", "Say what you know and what you do not know.",
  "Solve the problem before selling the solution.", "Sell outcomes, not hype.", "Use facts before making decisions.", "Pause before reacting under pressure.",
  "Keep commitments or communicate early when a commitment changes.", "Prepare before important conversations.", "Know the customer's problem before presenting an offer.",
  "Ask for the next step instead of forcing a sale.", "Know your price and your boundary.", "Look for mutual value in negotiation.", "Treat rejection as information, not identity.",
  "Receive criticism without losing professional control.", "Track revenue, costs, profit and cash flow.", "Record evidence instead of relying on feelings.", "Finish important work before adding more work.",
  "Build systems that make good behavior easier.", "Do not invent credentials or experience.", "Do not promise what you cannot deliver.", "Be on time and prepared.",
  "Protect customer trust.", "Review results and adjust the next action.", "Use technology to reduce repeated work.", "Document important decisions.",
  "Make the next useful action obvious.", "Practice before high-stakes conversations.", "Let consistent behavior prove the identity."
];

const phasePlans = [
  { name: "Foundation", behaviors: ["Slow down before responding.", "Ask before assuming.", "Finish one important task.", "Prepare before starting.", "Keep one small commitment.", "Listen without interrupting.", "Speak in simple sentences.", "Record evidence instead of feelings.", "Review what you actually did."], phrases: ["Let me make sure I understand.", "What is the main problem you want solved?", "Let me check the facts before I answer.", "Here is what I can do.", "Here is what I cannot confirm yet.", "What would a good result look like?", "I will follow up by the time we agreed.", "Let me write that down.", "The next step is clear."], actions: ["Write your 30-second company introduction.", "Write three problems your service can solve.", "Identify five potential customer types.", "Write your top five professional standards.", "Create a simple daily work block.", "Contact one potential customer.", "Ask one person about a business problem they have.", "Record one real example of professional behavior.", "Review the first eight days and choose one behavior to strengthen."] },
  { name: "Communication", behaviors: ["Listen first.", "Use fewer words.", "Ask one follow-up question.", "Do not interrupt.", "State the point first.", "Confirm understanding.", "Use professional language.", "Practice calm speech.", "Review one conversation."], phrases: ["Tell me more about that.", "What have you already tried?", "What is causing the biggest delay?", "What result do you need?", "Let me repeat that back to you.", "I understand the issue.", "I need one more detail before I answer.", "Here is the clearest way I see it.", "What should we do next?"], actions: ["Practice your introduction five times aloud.", "Have one discovery conversation.", "Ask three open-ended questions.", "Explain your service without technical jargon.", "Record yourself giving a 30-second explanation.", "Ask a customer or contact what they value most.", "Practice answering a difficult question calmly.", "Use one new professional phrase in a real conversation.", "Write what worked and what you will change next time."] },
  { name: "Discovery", behaviors: ["Be curious before persuasive.", "Look for the root problem.", "Ask for examples.", "Clarify the desired result.", "Separate symptoms from causes.", "Take notes.", "Do not rush to pitch.", "Summarize the problem.", "Review discovery quality."], phrases: ["What is happening today?", "How does that affect the business?", "How often does this happen?", "What does it cost you in time or money?", "Who is affected by this problem?", "What have you tried?", "What would you change first?", "So the main issue is…", "Would solving that be useful?"], actions: ["Write ten discovery questions.", "Interview one business owner about a problem.", "Ask how the problem is handled today.", "Document one customer workflow.", "Identify one repeated manual task.", "Identify one measurable customer outcome.", "Summarize one customer's problem in three sentences.", "Turn one problem into a possible service.", "Review your discovery notes and remove assumptions."] },
  { name: "Sales", behaviors: ["Lead with the problem.", "Be direct about value.", "Ask for the next step.", "Do not argue with objections.", "Stay calm after rejection.", "Follow up when promised.", "Use evidence.", "Know your offer.", "Review the conversation."], phrases: ["Based on what you told me, the main issue is…", "Here is the result this service is designed to produce.", "Would you like to look at the next step?", "What concerns you most about the offer?", "What would make this a better fit?", "I understand.", "Let me show you exactly what is included.", "Here is the boundary of the service.", "I will follow up on the date we agreed."], actions: ["Write one clear service offer.", "Send one truthful outreach message.", "Have one sales conversation.", "Handle one objection without arguing.", "Ask one prospect for a next step.", "Follow up with one previous contact.", "Write three reasons a customer should buy your service.", "Review one sales conversation and identify one improvement.", "Count your outreach, conversations and next steps for the week."] },
  { name: "Negotiation", behaviors: ["Prepare before negotiating.", "Know your minimum acceptable result.", "Ask about interests.", "Offer tradeoffs instead of discounts first.", "Stay calm.", "Do not agree under pressure.", "Document agreements.", "Protect the relationship.", "Review the outcome."], phrases: ["What matters most to you here?", "Here is what I can offer.", "If we add that, we would need to change the scope.", "I can do A or B; I cannot do both at that price.", "Let me think through that before I commit.", "Here is my boundary.", "What tradeoff would work for you?", "Let us confirm the agreement.", "I will send the details in writing."], actions: ["Write your ideal outcome for one offer.", "Write your minimum acceptable outcome.", "Write three tradeoffs you can offer.", "Practice a price objection aloud.", "Practice saying no professionally.", "Negotiate one small real-world issue calmly.", "Write down one agreement after a conversation.", "Review whether you protected your boundary.", "Create your personal negotiation checklist."] },
  { name: "Delivery", behaviors: ["Set clear expectations.", "Document the work.", "Communicate early.", "Check quality before delivery.", "Track deadlines.", "Close loops.", "Ask for feedback.", "Fix problems without hiding them.", "Review the result."], phrases: ["Here is what will be delivered.", "Here is the deadline.", "Here is what I need from you.", "I found an issue and I am addressing it.", "The work is ready for review.", "Here is the status.", "What needs to change?", "I will correct that.", "The task is complete."], actions: ["Write a simple delivery checklist.", "Create a customer onboarding checklist.", "Define what a completed service looks like.", "Create a quality-control step.", "Document one workflow.", "Create a follow-up schedule.", "Ask for feedback after one completed task.", "Fix one process that caused unnecessary work.", "Review your delivery system and remove one weak step."] },
  { name: "Systems", behaviors: ["Look for repeatable work.", "Document before automating.", "Use checklists.", "Track useful metrics.", "Reduce unnecessary steps.", "Keep data organized.", "Protect customer information.", "Test before relying on a system.", "Review system performance."], phrases: ["This should be repeatable.", "Let us document the process first.", "What can be automated safely?", "What information do we need?", "What is the success metric?", "What happens when this fails?", "Who owns this step?", "Let us test it before using it live.", "The system should make the next action clear."], actions: ["Document one repeated task step by step.", "Turn one repeated task into a checklist.", "Choose three business metrics to track.", "Create a simple customer record structure.", "Identify one task that can be automated.", "Test one small automation or tool.", "Create a backup/check step for important data.", "Measure time saved by one system.", "Review your systems and keep only useful ones."] },
  { name: "Leadership", behaviors: ["Own outcomes.", "Set clear expectations.", "Delegate clearly.", "Give useful feedback.", "Receive feedback without defensiveness.", "Communicate problems early.", "Make decisions with available facts.", "Protect standards.", "Review leadership behavior."], phrases: ["I own this outcome.", "Here is the standard.", "Here is what needs to happen next.", "What support do you need?", "What did we learn?", "What is the next decision?", "I will address the issue.", "Let us agree on the owner and deadline.", "Here is what I will improve."], actions: ["Write your leadership standards.", "Give one clear instruction to another person.", "Practice delegating a small task.", "Ask for honest feedback.", "Respond to criticism without defending yourself.", "Set one clear deadline.", "Resolve one small conflict professionally.", "Review one decision you made as a leader.", "Write the leadership behavior you will carry forward."] },
  { name: "Growth", behaviors: ["Think in systems.", "Measure before changing.", "Protect quality while growing.", "Prioritize high-value work.", "Keep learning.", "Build relationships.", "Ask for referrals ethically.", "Review revenue and costs.", "Choose the next growth experiment."], phrases: ["What is the highest-value next action?", "What evidence supports that?", "What would we measure?", "What is the smallest useful test?", "What would make this scalable?", "What does the customer actually need?", "What is the cost of this decision?", "What did the numbers show?", "What is the next experiment?"], actions: ["Review your revenue and costs.", "Identify your strongest service.", "Identify your weakest business process.", "Ask one satisfied contact for a referral.", "Test one small improvement to your offer.", "Review your customer acquisition activity.", "Write one growth experiment.", "Measure the result of one experiment.", "Choose the next 30-day business priority."] },
  { name: "Integration", behaviors: ["Act professionally without prompting.", "Use your rules under pressure.", "Keep your standards when tired.", "Stay truthful when challenged.", "Choose evidence over emotion.", "Complete the next useful action.", "Review behavior daily.", "Repeat what works.", "Operate from the integrated identity."], phrases: ["I will check the facts.", "Let me understand the problem first.", "Here is what I can commit to.", "I do not know yet; I will find out.", "Here is the next step.", "I can explain that clearly.", "I will not overpromise.", "Let us confirm the result we want.", "This is how I operate professionally."], actions: ["Run a full identity review.", "Complete one difficult business conversation.", "Practice your entire introduction and offer aloud.", "Run a complete discovery conversation.", "Run a complete sales conversation.", "Review one negotiation using your rules.", "Audit one customer delivery process.", "Review all 90-day evidence.", "Write your next 90-day operating plan."] }
];

const trainingDays = phasePlans.flatMap((phase, phaseIndex) => phase.behaviors.map((behavior, i) => ({ day: phaseIndex * 9 + i + 1, phase: phase.name, behavior, phrase: phase.phrases[i], action: phase.actions[i] })));

function initialState() { return { passed: [], learned: [], scores: {}, scenarioLevel: 0, scenarioScores: [], history: [], daily: {}, profile: {}, complete: false, trainingStart: today(), memory: {}, audits: {}, finalGate: null, manualVersion: 1, finalTestIndex: 0 }; }
function today() { return new Date().toISOString().slice(0, 10); }
function dayNumber(start) { const a = new Date(`${start}T00:00:00Z`).getTime(); const b = new Date(`${today()}T00:00:00Z`).getTime(); return Math.max(1, Math.min(90, Math.floor((b - a) / 86400000) + 1)); }
function Card({ title, children }) { return <div className="card"><small>{title}</small>{children}</div>; }
function Title({ title, sub }) { return <div className="title"><div className="eyebrow">TRAINING MODULE</div><h2>{title}</h2><p>{sub}</p></div>; }
function Hero({ s, streak }) { return <header className="hero"><div><div className="eyebrow">EXECUTIVE TRAINING SYSTEM</div><h1>TECH ENTREPRENEUR<br />IDENTITY TRAINING</h1><p>Build the behavior. Practice the behavior. Prove the behavior.</p></div><div className="heroStat"><strong>{s.complete ? "INTEGRATION" : "PHASE 1"}</strong><span>{streak ? `${streak}-day training streak` : "Start today's training"}</span></div></header>; }

function Dashboard({ s, streak, dailyScore, dailyDone, progress, passedCount, setTab, day }) {
  const t = trainingDays[day - 1];
  return <><Hero s={s} streak={streak} /><div className="grid"><Card title="Today's score"><b>{dailyScore}%</b><span>{dailyDone}/{dailyItems.length} daily actions complete</span></Card><Card title="Training streak"><b>{streak} day{streak === 1 ? "" : "s"}</b><span>Consecutive training days</span></Card><Card title="Phase 1 progress"><b>{progress}%</b><span>{passedCount}/{sections.length} sections passed</span></Card></div><div className="grid"><Card title="90-day program"><b>Day {day}/90</b><span>{t.phase}</span></Card><Card title="Scenario level"><b>Level {Math.min(s.scenarioLevel + 1, scenarios.length)}</b><span>{s.scenarioScores.length} attempts recorded</span></Card><Card title="Memory recall"><b>{Object.keys(s.memory || {}).length}</b><span>Training days with recall recorded</span></Card></div><section className="panel"><h2>Today's Mission</h2><p><strong>Behavior:</strong> {t.behavior}</p><p><strong>Say:</strong> {t.phrase}</p><p><strong>Do:</strong> {t.action}</p><p><strong>Do not:</strong> guess, exaggerate, overpromise, or skip the evidence.</p><div className="progress"><i style={{ width: `${dailyScore}%` }} /></div><button onClick={() => setTab("daily")}>CONTINUE TRAINING</button></section><section className="panel"><h2>Operating Identity</h2><p><strong>{identityManual.identity.name}</strong> — {identityManual.identity.company}</p><p>{identityManual.mission}</p><p><strong>Motto:</strong> {identityManual.motto}</p></section></>;
}

function Lesson({ id, answer, setAnswer, s, markLearn, test, feedback, setActive }) { const x = sections.find(a => a[0] === id); const l = lessons[id]; return <div className="modal"><div className="modalInner"><button className="close" onClick={() => setActive(null)}>×</button><div className="eyebrow">SECTION TRAINING</div><h2>{x[1]}</h2><h4>WHAT YOU ARE LEARNING</h4><p>{l[0]}</p><h4>RULES</h4><ul>{l[1].map(r => <li key={r}>{r}</li>)}</ul><h4>REQUIRED PRACTICE</h4><p>{l[2]}</p><textarea value={answer} onChange={e => setAnswer(e.target.value)} /><div className="actions"><button onClick={() => markLearn(id)}>MARK LEARNING COMPLETE</button><button disabled={!s.learned.includes(id)} onClick={() => test(id)}>SUBMIT STRICT TEST</button></div>{feedback && <div className={feedback.startsWith("PASSED") ? "success" : "error"}>{feedback}</div>}</div></div>; }

function Phase1({ s, active, setActive, setAnswer, setFeedback, answer, markLearn, test, feedback, passedCount, finalTest }) { return <><Title title="Phase 1 — Identity Profile" sub="Learn each section, practice it, then pass a strict test. Answers are judged for required facts, not length." /><div className="sectionList">{sections.map((x, i) => { const passed = s.passed.includes(x[0]); const unlocked = i === 0 || s.passed.includes(sections[i - 1][0]); return <div className={`sectionRow ${passed ? "passed" : ""} ${!unlocked ? "locked" : ""}`} key={x[0]}><div className="num">{passed ? "✓" : i + 1}</div><div><h3>{x[1]}</h3><p>{x[2].join(" • ")}</p></div><button disabled={!unlocked} onClick={() => { setActive(x[0]); setAnswer(""); setFeedback(""); }}>{passed ? "REVIEW" : "OPEN"}</button></div>; })}</div>{active && <Lesson id={active} answer={answer} setAnswer={setAnswer} s={s} markLearn={markLearn} test={test} feedback={feedback} setActive={setActive} />}{passedCount === sections.length && <div className="panel"><h2>Phase 1 Final Gate</h2><p>This gate tests the actual company manual. You must answer each recall item accurately. One weak answer does not pass the gate.</p><button onClick={finalTest}>RUN FINAL GATE</button>{feedback && <div className={feedback.startsWith("PASSED") ? "success" : "error"}>{feedback}</div>}</div>}</>; }

function Daily({ todayData, dailyScore, toggleDaily, review, setReview, saveReview, day }) { const t = trainingDays[day - 1]; return <><Title title="Daily Training" sub="The program runs through 90 days. Each day gives you exactly what to practice, say, do, and prove." /><div className="panel"><div className="eyebrow">DAY {day} OF 90 — {t.phase}</div><h2>Behavior of the Day</h2><p>{t.behavior}</p><h2>Verbal Practice</h2><p>{t.phrase}</p><p>Say it aloud five times. Then use the principle in a real business conversation when appropriate.</p><h2>Real-World Business Action</h2><p>{t.action}</p><h2>Do Not</h2><p>Do not invent credentials, results, customers, technical facts, or promises.</p></div><div className="panel"><h2>Today's checklist — {dailyScore}%</h2>{dailyItems.map((x, i) => <label className="check" key={x}><input type="checkbox" checked={!!(todayData.items || {})[i]} onChange={() => toggleDaily(i)} /><span>{x}</span></label>)}</div><div className="panel"><h2>End-of-Day Evidence</h2><p>Record what you actually did, what happened, and what you will repeat.</p><textarea value={review} onChange={e => setReview(e.target.value)} /><button onClick={saveReview}>SAVE REVIEW</button>{todayData.review && <div className="success">Today's review is saved.</div>}</div></>; }

function Scenarios({ s, scenarioAnswer, setScenarioAnswer, submitScenario, feedback }) { const level = Math.min(s.scenarioLevel, scenarios.length - 1); const sc = scenarios[level]; return <><Title title="Scenario Training" sub="Clients, customers, and business pressure test the identity. Passing requires the required behavior, not a long answer." /><div className="levelbar">{scenarios.map((a, i) => <span className={i <= level ? "on" : ""} key={a[0]}>L{i + 1}</span>)}</div><div className="panel"><div className="eyebrow">LEVEL {level + 1} — {sc[0]}</div><h2>{sc[1]}</h2><textarea value={scenarioAnswer} onChange={e => setScenarioAnswer(e.target.value)} /><button onClick={submitScenario}>SUBMIT STRICT RESPONSE</button>{feedback && <div className={feedback.startsWith("PASSED") ? "success" : "error"}>{feedback}</div>}</div><div className="panel"><h2>Scenario History</h2>{s.scenarioScores.length === 0 ? <p>No scenario attempts recorded yet.</p> : s.scenarioScores.slice(-10).reverse().map((x, i) => <div className="rule" key={i}>{x.date} — Level {x.level} — {x.score}% — {x.result}</div>)}</div></>; }

function Memory({ s, day, memoryAnswer, setMemoryAnswer, memoryIndex, setMemoryIndex, saveMemory }) { const item = recallItems[memoryIndex % recallItems.length]; const current = s.memory?.[day] || {}; return <><Title title="Memory Training" sub="Read the manual. Cover it. Recall it. Write it. Then apply it. Length alone never counts as accurate recall." /><div className="grid"><Card title="Day"><b>{day}/90</b><span>Current training day</span></Card><Card title="Recall items"><b>{recallItems.length}</b><span>Core manual checks</span></Card><Card title="Recorded"><b>{Object.keys(s.memory || {}).length}</b><span>Days with saved recall</span></Card></div><div className="panel"><div className="eyebrow">RECALL ITEM {memoryIndex % recallItems.length + 1} OF {recallItems.length}</div><h2>{item.question}</h2><p>Answer from memory before revealing the reference answer.</p><textarea value={memoryAnswer} onChange={e => setMemoryAnswer(e.target.value)} /><button onClick={() => saveMemory(item, memoryAnswer)}>REVEAL AND GRADE RECALL</button>{current.answer && <div className={current.recalled ? "success" : "error"}><strong>Reference:</strong> {item.answer}<br /><br /><strong>Your recall:</strong> {current.answer}<br /><br />{current.recalled ? "Recall passed." : "Recall did not pass. Repeat this item."}</div>}</div><div className="actions"><button onClick={() => setMemoryIndex((memoryIndex + 1) % recallItems.length)}>NEXT MEMORY ITEM</button></div></>; }

function Audit({ s, setS, day, feedback, setFeedback }) { const [metrics, setMetrics] = useState({}); const [evidence, setEvidence] = useState(""); const [score, setScore] = useState(""); const t = trainingDays[day - 1]; const saved = s.audits?.[today()]; const metricNames = ["Customers contacted", "Sales conversations", "Problems solved", "Proposals", "Revenue", "Skills learned", "Systems created", "Difficult conversations", "Commitments kept"]; function save() { setS(prev => ({ ...prev, audits: { ...prev.audits, [today()]: { metrics, evidence, score, behavior: t.behavior, phrase: t.phrase, action: t.action } } })); setFeedback("Identity audit saved."); } return <><Title title="Identity Audit" sub="Compare the person you said you would become with what you actually did." /><div className="panel"><h2>Today's Behavior</h2><p>{t.behavior}</p><h2>Evidence</h2><p>Write facts. What did you actually say or do?</p><textarea value={evidence} onChange={e => setEvidence(e.target.value)} /><h2>Professional Behavior Score</h2><input type="number" min="0" max="100" value={score} onChange={e => setScore(e.target.value)} /><h2>Business Evidence</h2>{metricNames.map(x => <label className="metric" key={x}><span>{x}</span><input type="number" min="0" value={metrics[x] || ""} onChange={e => setMetrics({ ...metrics, [x]: e.target.value })} /></label>)}<button onClick={save}>SAVE AUDIT</button>{feedback && <div className="success">{feedback}</div>}{saved && <div className="success">Saved audit exists for today.</div>}</div></>; }

function Final({ passedCount, finalTest, feedback, s, finalItem, finalAnswer, setFinalAnswer, submitFinalItem }) { return <><Title title="Final Gate" sub="This is an oral/written recall test of the actual Fogle Unlimited identity manual." /><div className="panel"><h2>{s.finalGate?.passed ? "PHASE 1 PASSED" : passedCount === sections.length ? `FINAL GATE — ITEM ${s.finalGate?.index ? s.finalGate.index : 1} OF ${recallItems.length}` : "LOCKED"}</h2><p>{passedCount}/{sections.length} Phase 1 sections passed.</p>{passedCount === sections.length && !s.finalGate?.passed && <><p><strong>Question:</strong> {finalItem.question}</p><textarea value={finalAnswer} onChange={e => setFinalAnswer(e.target.value)} /><button onClick={submitFinalItem}>SUBMIT FINAL-GATE ANSWER</button></>}{s.finalGate?.passed && <div className="success">Final gate passed on {s.finalGate.date}. The 90-day integration program is active.</div>}{feedback && <div className={feedback.startsWith("PASSED") ? "success" : "error"}>{feedback}</div>}</div></>; }

function Settings({ s, update, setFeedback, feedback, reset }) { const [prompt, setPrompt] = useState(s.profile?.prompt || ""); return <><Title title="Settings" sub="Your training data is stored locally in this browser." /><div className="panel"><h2>Identity Training Prompt</h2><p>Save your master prompt here as the instruction layer for the training system. The company manual and 90-day training data are already part of the application.</p><textarea value={prompt} onChange={e => setPrompt(e.target.value)} /><button onClick={() => { update({ profile: { ...(s.profile || {}), prompt } }); setFeedback("Identity prompt saved locally."); }}>SAVE</button>{feedback && <div className="success">{feedback}</div>}</div><div className="panel"><h2>Current Operating Identity</h2><p><strong>{identityManual.identity.name}</strong> — {identityManual.identity.company}</p><p><strong>Internal target:</strong> {identityManual.identity.internalTarget}</p><p>{identityManual.identity.rule}</p><p><strong>Mission:</strong> {identityManual.mission}</p><p><strong>Purpose:</strong> {identityManual.purpose}</p><p><strong>Values:</strong> {identityManual.values.join(" • ")}</p><p><strong>Motto:</strong> {identityManual.motto}</p></div><div className="panel"><h2>Training Rules</h2><ul>{identityManual.operatingDoctrine.map(x => <li key={x}>{x}</li>)}</ul><p><strong>Strict testing:</strong> accurate recall, scenario application, repeated attempts, and increasing difficulty.</p></div><div className="panel danger"><h2>Reset Training</h2><p>This erases local training progress on this browser.</p><button className="dangerBtn" onClick={reset}>RESET SYSTEM</button></div></>; }

function IdentityProfile({ s, update, setFeedback, feedback }) { const fields = [["mission", "Mission", "What are we building and why?"], ["values", "Values", "What core principles guide our decisions?"], ["standards", "Standards", "What professional standards will we always follow?"], ["strengths", "Strengths", "What do we already do well?"], ["skills", "Skills to Build", "What skills do we need to develop?"], ["goals", "Business Goals", "What specific business results do we want to see?"]]; return <><Title title="Identity Profile" sub="Your profile supplies personal details; the verified Fogle Unlimited manual supplies the fixed company facts used by the tests." /><div className="panel"><h2>Fixed Company Identity</h2><p><strong>Mr. Fogle — Fogle Unlimited — internal target: the $80 million man.</strong></p><p>{identityManual.mission}</p><p><strong>Customer problem/result:</strong> {identityManual.customerProblem}</p><p><strong>30-second service:</strong> {identityManual.service30}</p></div><div className="panel">{fields.map(([key, label, question]) => <div key={key}><h2>{label}</h2><p>{question}</p><textarea value={s.profile?.[key] || ""} onChange={e => update({ profile: { ...(s.profile || {}), [key]: e.target.value } })} /></div>)}<button onClick={() => setFeedback("Identity profile saved locally.")}>SAVE PROFILE</button>{feedback && <div className="success">{feedback}</div>}</div></>; }

function normalize(text) { return text.toLowerCase().replace(/[^a-z0-9$ ]/g, " ").replace(/\s+/g, " ").trim(); }
function hasAll(text, terms) { const n = normalize(text); return terms.every(t => n.includes(normalize(t))); }
function requiredTermsForSection(id) { const map = { identity: ["Mr. Fogle", "Fogle Unlimited", "mission", "professional identity"], business: ["customer problem", "value", "revenue", "cost"], communication: ["listen", "simple words", "know", "do not know"], decision: ["facts", "options", "tradeoffs", "next action"], leadership: ["commitment", "communicate", "problem"], sales: ["discovery", "problem", "value", "next step"], negotiation: ["prepare", "boundary", "tradeoff"], emotion: ["pause", "facts", "pressure"], money: ["revenue", "cost", "profit", "cash flow"], standards: ["prepared", "honest", "commitments", "motto"] }; return map[id] || []; }

function App() {
  const [s, setS] = useState(() => { try { const raw = JSON.parse(localStorage.getItem(KEY)); return raw ? { ...initialState(), ...raw, trainingStart: raw.trainingStart || today(), memory: raw.memory || {}, audits: raw.audits || {}, finalGate: raw.finalGate || null } : initialState(); } catch { return initialState(); } });
  const [tab, setTab] = useState("dashboard"); const [active, setActive] = useState(null); const [answer, setAnswer] = useState(""); const [scenarioAnswer, setScenarioAnswer] = useState(""); const [feedback, setFeedback] = useState(""); const [review, setReview] = useState(""); const [memoryAnswer, setMemoryAnswer] = useState(""); const [memoryIndex, setMemoryIndex] = useState(0); const [finalAnswer, setFinalAnswer] = useState("");
  useEffect(() => { localStorage.setItem(KEY, JSON.stringify(s)); }, [s]);
  const date = today(); const todayData = s.daily[date] || {}; const passedCount = s.passed.length; const progress = Math.round((passedCount / sections.length) * 100); const dailyDone = Object.values(todayData.items || {}).filter(Boolean).length; const dailyScore = Math.round((dailyDone / dailyItems.length) * 100); const day = dayNumber(s.trainingStart); const finalIndex = s.finalGate?.index || 0; const finalItem = recallItems[Math.min(finalIndex, recallItems.length - 1)];
  const streak = useMemo(() => { let count = 0; let d = new Date(); while (true) { const key = d.toISOString().slice(0, 10); const item = s.daily[key]; if (!item || !item.items || Object.values(item.items).filter(Boolean).length === 0) break; count++; d.setDate(d.getDate() - 1); } return count; }, [s.daily]);
  function update(patch) { setS(prev => ({ ...prev, ...patch })); }
  function toggleDaily(i) { const items = { ...(todayData.items || {}), [i]: !(todayData.items || {})[i] }; setS(prev => ({ ...prev, daily: { ...prev.daily, [date]: { ...(prev.daily[date] || {}), items } } })); }
  function markLearn(id) { update({ learned: [...new Set([...s.learned, id])] }); setFeedback("Learning recorded. The strict test remains required."); }
  function test(id) { const required = requiredTermsForSection(id); const ok = hasAll(answer, required); const score = ok ? 100 : Math.max(20, Math.round((required.filter(x => normalize(answer).includes(normalize(x))).length / required.length) * 100)); update({ scores: { ...s.scores, [id]: score }, passed: ok ? [...new Set([...s.passed, id])] : s.passed }); setFeedback(ok ? `PASSED — ${score}%. Required concepts recalled accurately.` : `FAILED — ${score}%. Missing required concepts: ${required.filter(x => !normalize(answer).includes(normalize(x))).join(", ")}. Review and retry.`); if (ok) setAnswer(""); }
  function submitScenario() { const n = normalize(scenarioAnswer); const required = ["problem", "question", "customer", "next step", "truthful", "scope", "boundary", "calm"]; const hits = required.filter(x => n.includes(x)); const score = Math.round((hits.length / required.length) * 100); const passed = score >= 75 && n.length >= 80; const level = Math.min(s.scenarioLevel + (passed ? 1 : 0), scenarios.length - 1); setS(prev => ({ ...prev, scenarioLevel: level, scenarioScores: [...prev.scenarioScores, { date, level: Math.min(prev.scenarioLevel + 1, scenarios.length), score, result: passed ? "PASSED" : "FAILED" }] })); setFeedback(passed ? `PASSED — ${score}%. Level advanced.` : `FAILED — ${score}%. Required behaviors were not demonstrated. Retry.`); setScenarioAnswer(""); }
  function saveReview() { if (!review.trim()) return; const existing = s.daily[date] || {}; setS(prev => ({ ...prev, daily: { ...prev.daily, [date]: { ...existing, review } }, history: [...prev.history.filter(x => x.date !== date), { date, dailyScore, review }] })); setFeedback("End-of-day review saved."); setReview(""); }
  function saveMemory(item, response) { const n = normalize(response); const exact = item.id === "mission" ? n === normalize(item.answer) : item.answer.split(/;|,|\./).filter(x => x.trim().length > 3).slice(0, 3).every(x => n.includes(normalize(x))); const recalled = exact || (response.trim().length >= 20 && item.id !== "mission" && n.includes(normalize(item.answer.split(" ").slice(0, 5).join(" ")))); setS(prev => ({ ...prev, memory: { ...prev.memory, [day]: { itemId: item.id, answer: response, reference: item.answer, recalled, date } } })); setFeedback(recalled ? "Recall passed for this item." : "Recall failed. Repeat the item until the required facts are accurate."); }
  function submitFinalItem() { const n = normalize(finalAnswer); const item = finalItem; const exactEnough = item.id === "mission" ? n === normalize(item.answer) : item.id === "values" ? identityManual.values.every(x => n.includes(normalize(x))) : item.id === "problem" ? hasAll(finalAnswer, ["Businesses waste time", "disorganized work", "simple systems", "less wasted time", "smoother operations"]) : item.id === "service" ? hasAll(finalAnswer, ["small businesses", "repetitive work", "digital systems", "workflows", "forms", "tracking", "automation", "save time", "reduce mistakes"]) : n.length >= 80; if (!exactEnough) { setFeedback("FAILED — this final-gate answer is not accurate enough. Review the manual and repeat the item."); setFinalAnswer(""); return; } const next = finalIndex + 1; if (next >= recallItems.length) { setS(prev => ({ ...prev, complete: true, finalGate: { passed: true, date, index: recallItems.length } })); setFeedback("PASSED — FINAL GATE COMPLETE. 90-DAY INTEGRATION IS ACTIVE."); setFinalAnswer(""); } else { setS(prev => ({ ...prev, finalGate: { ...(prev.finalGate || {}), passed: false, index: next, date } })); setFeedback(`PASSED — Item ${next} of ${recallItems.length} complete. Next item unlocked.`); setFinalAnswer(""); } }
  function finalTest() { if (passedCount !== sections.length) { setFeedback("FAILED — complete every locked Phase 1 section first."); return; } setS(prev => ({ ...prev, finalGate: { passed: false, index: 0, date } })); setTab("final"); setFeedback("FINAL GATE STARTED — answer each manual recall item accurately."); }
  function reset() { if (confirm("Erase all local training progress?")) { localStorage.removeItem(KEY); location.reload(); } }
  function render() {
    if (tab === "dashboard") return <Dashboard s={s} streak={streak} dailyScore={dailyScore} dailyDone={dailyDone} progress={progress} passedCount={passedCount} setTab={setTab} day={day} />;
    if (tab === "identity") return <IdentityProfile s={s} update={update} setFeedback={setFeedback} feedback={feedback} />;
    if (tab === "phase1") return <Phase1 s={s} active={active} setActive={setActive} setAnswer={setAnswer} setFeedback={setFeedback} answer={answer} markLearn={markLearn} test={test} feedback={feedback} passedCount={passedCount} finalTest={finalTest} />;
    if (tab === "daily") return <Daily todayData={todayData} dailyScore={dailyScore} toggleDaily={toggleDaily} review={review} setReview={setReview} saveReview={saveReview} day={day} />;
    if (tab === "scenarios") return <Scenarios s={s} scenarioAnswer={scenarioAnswer} setScenarioAnswer={setScenarioAnswer} submitScenario={submitScenario} feedback={feedback} />;
    if (tab === "memory") return <Memory s={s} day={day} memoryAnswer={memoryAnswer} setMemoryAnswer={setMemoryAnswer} memoryIndex={memoryIndex} setMemoryIndex={setMemoryIndex} saveMemory={saveMemory} />;
    if (tab === "audit") return <Audit s={s} setS={setS} day={day} feedback={feedback} setFeedback={setFeedback} />;
    if (tab === "final") return <Final passedCount={passedCount} finalTest={finalTest} feedback={feedback} s={s} finalItem={finalItem} finalAnswer={finalAnswer} setFinalAnswer={setFinalAnswer} submitFinalItem={submitFinalItem} />;
    if (tab === "settings") return <Settings s={s} update={update} setFeedback={setFeedback} feedback={feedback} reset={reset} />;
    return <Dashboard s={s} streak={streak} dailyScore={dailyScore} dailyDone={dailyDone} progress={progress} passedCount={passedCount} setTab={setTab} day={day} />;
  }
  return <div className="app"><aside><div className="brand">TE<span>IS</span></div><div className="brandSub">TECH ENTREPRENEUR<br />IDENTITY SYSTEM</div>{[["dashboard", "Dashboard"], ["identity", "Identity Profile"], ["phase1", "Phase 1 — Identity"], ["daily", "Daily Training"], ["scenarios", "Scenario Training"], ["memory", "Memory Training"], ["audit", "Identity Audit"], ["final", "Final Test"], ["settings", "Settings"]].map(([id, name]) => <button className={tab === id ? "nav active" : "nav"} key={id} onClick={() => { setTab(id); setFeedback(""); }}>{name}</button>)}<div className="sideProgress"><small>PHASE 1</small><div className="progress"><i style={{ width: `${progress}%` }} /></div><b>{progress}%</b></div></aside><main>{render()}</main></div>;
}

createRoot(document.getElementById("root")).render(<App />);
