import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import'./styles.css';
const KEY='te_identity_training_v1';
const sections=[
['identity','Professional Identity',['Professional identity','Mission','Values','Standards','Strengths','Weaknesses','Skills']],
['business','Business Knowledge',['Technology','Business models','Customers','Problems','Solutions','Value','Revenue','Costs','Basic business metrics']],
['communication','Communication',['Clear speaking','Active listening','Asking questions','Explaining ideas','Professional language','Handling uncertainty']],
['decision','Decision Making',['Facts','Options','Risks','Tradeoffs','Decisions','Follow-through']],
['leadership','Leadership',['Responsibility','Reliability','Communication','Delegation','Accountability','Problem solving']],
['sales','Sales',['Discovery','Customer problems','Value','Objections','Offers','Follow-up','Asking for the sale']],
['negotiation','Negotiation',['Preparation','Interests','Options','Boundaries','Tradeoffs','Agreement']],
['emotion','Emotional Control',['Rejection','Criticism','Pressure','Uncertainty','Failure','Difficult conversations']],
['money','Money',['Revenue','Expenses','Profit','Cash flow','Pricing','Saving','Reinvestment']],
['standards','Professional Standards',['Reliability','Preparation','Honesty','Follow-through','Professional appearance','Professional communication','Keeping commitments']]
];
const lessons={identity:{why:'A professional identity is a set of repeatable standards and behaviors, not a fictional character.',rules:['Use truthful facts.','Ask before assuming.','Practice the behavior you want to make normal.'],practice:'Write one professional standard you will follow today.'},business:{why:'Entrepreneurs solve real problems for specific people and create value that can support a business.',rules:['Start with the customer problem.','Know how value is created.','Track money clearly.'],practice:'Name one customer problem you can solve and the measurable result you want.'},communication:{why:'Clear communication reduces confusion and makes discovery, sales and leadership more effective.',rules:['Listen before answering.','Use simple words.','Say what you know and what you do not know.'],practice:'Explain one service in 30 seconds without jargon.'},decision:{why:'Good decisions use facts, options, tradeoffs and follow-through.',rules:['Separate facts from assumptions.','Choose a next action.','Review results.'],practice:'Take one current decision and write the facts, options and next action.'},leadership:{why:'Leadership is demonstrated through responsibility, reliability and useful action.',rules:['Own commitments.','Communicate early.','Solve problems.'],practice:'Identify one commitment you can complete today.'},sales:{why:'Sales starts with understanding a problem and matching a truthful offer to it.',rules:['Discover before pitching.','Sell outcomes, not hype.','Ask for the next step.'],practice:'Write three discovery questions for a potential customer.'},negotiation:{why:'Negotiation works better when interests, boundaries and tradeoffs are clear.',rules:['Prepare first.','Know your boundary.','Look for mutual value.'],practice:'Write your ideal outcome, acceptable outcome and walk-away boundary for a real discussion.'},emotion:{why:'Professional behavior includes staying deliberate when rejection, criticism or uncertainty appears.',rules:['Pause before reacting.','Separate feedback from identity.','Return to facts and objectives.'],practice:'Describe one pressure situation and write the response you want to practice.'},money:{why:'A business must understand revenue, costs, profit, cash flow and pricing.',rules:['Know the numbers.','Protect cash flow.','Price from value and costs.'],practice:'List one revenue source and three costs connected to it.'},standards:{why:'Professional reputation is built by repeated observable behavior.',rules:['Be on time.','Prepare.','Do what you said you would do.'],practice:'Choose one commitment and record exactly when you will complete it.'}};
const scenarios=[['Low pressure','Introduce yourself to a new business contact. Explain what you do and ask one useful question.'],['Networking','You meet an owner who says they are busy. Respond professionally and ask for a better time.'],['Sales','A prospect says, “I already have someone.” Respond without arguing.'],['Pricing','A prospect says your price is too high. Ask a useful question before responding.'],['Negotiation','A buyer wants more work for the same price. Explain your boundary and offer a tradeoff.'],['Difficult customer','A customer is upset about a missed expectation. Respond calmly and propose the next step.'],['High-pressure presentation','You are asked a technical question you do not know. Answer without pretending to know.']];
function initial(){return{phase:1,passed:[],learned:[],scores:{},daily:{date:'',items:{}},scenarioLevel:0,audits:[],profile:{},complete:false}}
function App(){const[s,setS]=useState(()=>{try{return JSON.parse(localStorage.getItem(KEY))||initial()}catch{return initial()}});const[tab,setTab]=useState('dashboard');const[active,setActive]=useState(null);const[answer,setAnswer]=useState('');const[scenarioAnswer,setScenarioAnswer]=useState('');const[feedback,setFeedback]=useState(null);const[profile,setProfile]=useState(s.profile||{});useEffect(()=>localStorage.setItem(KEY,JSON.stringify(s)),[s]);
const passedCount=s.passed.length;const phase1Done=passedCount===sections.length;const progress=Math.round((passedCount/sections.length)*100);const next=sections.find(x=>!s.passed.includes(x[0]));
function unlock(i){return i===0||s.passed.includes(sections[i-1][0])}
function markLearn(id){setS({...s,learned:[...new Set([...s.learned,id])]});}
function test(id){const q=answer.trim();if(!q)return;const good=q.length>=25;const score=good?90:40;setS({...s,scores:{...s.scores,[id]:score},passed:good?[...new Set([...s.passed,id])]:s.passed});setFeedback(good?`Passed — ${score}%`:`Failed — ${score}%. Review the lesson and retake.`);setAnswer('')}
function finalTest(){const score=passedCount===sections.length?100:0;setS({...s,complete:score===100});setFeedback(score? 'SYSTEM COMPLETE — Phase 1 passed. Phase 2 is unlocked.':'Complete every Phase 1 section first.')}
function reset(){if(confirm('This will erase your local training progress. Continue?')){localStorage.removeItem(KEY);location.reload()}}
const today=new Date().toISOString().slice(0,10);const dailyItems=['Identity review','Verbal practice','Scenario drill','Real-world business action','Behavior of the day','Evening review'];const done=s.daily.date===today?s.daily.items:{};function toggleDaily(i){setS({...s,daily:{date:today,items:{...done,[i]:!done[i]}}})}
function render(){if(tab==='dashboard')return <Dashboard/>;if(tab==='phase1')return <Phase1/>;if(tab==='phase2')return <Phase2/>;if(tab==='daily')return <Daily/>;if(tab==='scenarios')return <Scenarios/>;if(tab==='memory')return <Memory/>;if(tab==='audit')return <Audit/>;if(tab==='final')return <Final/>;return <Settings/>}
function Dashboard(){return <><Hero/><div className="grid"><Card title="Current phase"><b>Phase {phase1Done?'2':'1'}</b><span>{phase1Done?'Identity Integration':'Identity Profile'}</span></Card><Card title="Progress"><b>{progress}%</b><span>{passedCount}/{sections.length} sections passed</span></Card><Card title="Next action"><b>{next?`Learn: ${next[1]}`:'Phase 1 Final Test'}</b><span>{next?'Complete the next lesson and test.':'All sections passed.'}</span></Card></div><section className="panel"><h2>Today's training</h2><p>Use the checklist below. The goal is practice, not endless reading.</p><div className="progress"><i style={{width:`${Math.round(Object.values(done).filter(Boolean).length/6*100)}%`}}/></div><button onClick={()=>setTab('daily')}>CONTINUE TRAINING</button></section><section className="panel"><h2>Training path</h2><div className="path">{['LEARN','PRACTICE','TEST','PASS','UNLOCK','INTEGRATE','REAL ACTION','REPETITION','STRESS TEST','FINAL TEST'].map((x,i)=><span key={x} className={i<passedCount?'on':''}>{x}</span>)}</div></section></>}
function Hero(){return <header className="hero"><div><div className="eyebrow">EXECUTIVE TRAINING SYSTEM</div><h1>TECH ENTREPRENEUR<br/>IDENTITY TRAINING</h1><p>Build the behavior. Practice the behavior. Prove the behavior.</p></div><div className="heroStat"><strong>{s.complete?'COMPLETE':`PHASE ${phase1Done?'2':'1'}`}</strong><span>{s.complete?'Integration status ready':'Sequential progression active'}</span></div></header>}
function Card({title,children}){return <div className="card"><small>{title}</small>{children}</div>}
function Phase1(){return <><Title title="Phase 1 — Identity Profile" sub="Learn each section, practice it, then pass its test to unlock the next."/><div className="sectionList">{sections.map((x,i)=>{const ok=s.passed.includes(x[0]),can=unlock(i);return <div className={`sectionRow ${ok?'passed':''} ${!can?'locked':''}`} key={x[0]}><div className="num">{ok?'✓':i+1}</div><div><h3>{x[1]}</h3><p>{x[2].join(' • ')}</p></div><button disabled={!can} onClick={()=>{setActive(x[0]);setAnswer('');setFeedback(null)}}>{ok?'REVIEW':'OPEN'}</button></div>})}</div>{active&&<Lesson id={active}/>} {phase1Done&&<div className="panel"><h2>Phase 1 Final Test</h2><p>All ten sections are passed. Complete the final gate to unlock Phase 2.</p><button onClick={finalTest}>START PHASE 1 FINAL TEST</button></div>}</>}
function Lesson({id}){const x=sections.find(a=>a[0]===id),l=lessons[id],isPassed=s.passed.includes(id);return <div className="modal"><div className="modalInner"><button className="close" onClick={()=>setActive(null)}>×</button><div className="eyebrow">SECTION TRAINING</div><h2>{x[1]}</h2><h4>WHAT YOU ARE LEARNING</h4><p>{l.why}</p><h4>RULES</h4><ul>{l.rules.map(r=><li key={r}>{r}</li>)}</ul><h4>PRACTICE</h4><p>{l.practice}</p><textarea placeholder="Complete the practice exercise here…" value={answer} onChange={e=>setAnswer(e.target.value)}/><div className="actions"><button onClick={()=>markLearn(id)}>MARK LEARNING COMPLETE</button><button disabled={!s.learned.includes(id)} onClick={()=>test(id)}>SUBMIT TEST</button></div>{feedback&&<div className={feedback.startsWith('Passed')?'success':'error'}>{feedback}</div>}{!isPassed&&s.learned.includes(id)&&<p className="muted">Test rule: provide a clear applied response of at least 25 characters. Retake until passed.</p>}</div></div>}
function Phase2(){if(!phase1Done)return <Locked title="Phase 2 — Identity Integration" text="Pass all Phase 1 sections first."/>;return <><Title title="Phase 2 — Identity Integration Engine" sub="Move desired behaviors from conscious → practiced → repeated → automatic."/><div className="grid"><Card title="Observable behavior"><b>THINK → SAY → DO</b><span>Define behavior in visible terms.</span></Card><Card title="Installation loop"><b>CUE → BEHAVIOR</b><span>Reward → repetition.</span></Card><Card title="Anti-procrastination"><b>REAL ACTION</b><span>Practice must reach the real world.</span></Card></div><div className="panel"><h2>Automatic response rules</h2>{['IF I feel nervous → slow my speech.','IF I do not know → say so and find the answer.','IF I get rejected → ask one useful question.','IF challenged → listen before responding.','IF pressured → pause before deciding.'].map(x=><div className="rule" key={x}>{x}</div>)}<p className="muted">The MVP includes the core engine. Additional personalized rules can be generated from your profile.</p></div></>}
function Daily(){return <><Title title="Daily Training" sub="30 minutes of structured practice plus one real-world action."/><div className="panel"><h2>Today's checklist</h2>{dailyItems.map((x,i)=><label className="check" key={x}><input type="checkbox" checked={!!done[i]} onChange={()=>toggleDaily(i)}/><span>{x}</span></label>)}</div></>}
function Scenarios(){const level=Math.min(s.scenarioLevel,6);const sc=scenarios[level];return <><Title title="Scenario Training" sub="Progress through increasingly difficult business situations."/><div className="levelbar">{scenarios.map((a,i)=><span className={i<=level?'on':''} key={a[0]}>L{i+1}</span>)}</div><div className="panel"><div className="eyebrow">LEVEL {level+1} — {sc[0]}</div><h2>{sc[1]}</h2><textarea value={scenarioAnswer} onChange={e=>setScenarioAnswer(e.target.value)} placeholder="Type your response…"/><button onClick={()=>{setFeedback(scenarioAnswer.trim().length>=30?'Strong enough to advance. Review clarity, listening and emotional control.':'Response too short. Try again with a complete professional response.');if(scenarioAnswer.trim().length>=30&&level<6)setS({...s,scenarioLevel:level+1})}}>SUBMIT RESPONSE</button>{feedback&&<div className="success">{feedback}</div>}</div></>}
function Memory(){return <><Title title="Memory Training" sub="Recall beats passive reading."/><div className="grid"><Card title="NEW"><b>Rules</b><span>Review the rules from current sections.</span></Card><Card title="LEARNING"><b>Flashcards</b><span>Recall before revealing the answer.</span></Card><Card title="PRACTICED"><b>Scenarios</b><span>Apply rules under pressure.</span></Card><Card title="MASTERED"><b>Evidence</b><span>Demonstrate the behavior repeatedly.</span></Card></div><div className="panel"><h2>Quick recall</h2><p>What is the core loop?</p><button onClick={()=>setFeedback('IDENTITY → LEARN → PRACTICE → TEST → PASS → REAL ACTION → FEEDBACK → REPETITION')}>REVEAL</button>{feedback&&<div className="success">{feedback}</div>}</div></>}
function Audit(){return <><Title title="Weekly Identity Audit" sub="Measure observable evidence, not feelings."/><div className="panel"><h2>Evidence</h2>{['Customers contacted','Sales conversations','Problems solved','Proposals','Revenue','Skills learned','Systems created','Difficult conversations','Commitments kept'].map((x,i)=><label className="metric" key={x}><span>{x}</span><input type="number" min="0" defaultValue="0"/></label>)}<button onClick={()=>setFeedback('Audit saved for this session. Use the numbers as evidence of behavior.')}>SAVE AUDIT</button>{feedback&&<div className="success">{feedback}</div>}</div></>}
function Final(){return <><Title title="Final Test" sub="The final gate is available after Phase 1 is complete."/>{!phase1Done?<Locked title="Final Test Locked" text="Complete all Phase 1 sections first."/>:<div className="panel"><h2>Blind comprehensive test</h2><p>For this MVP, Phase 1 completion is the gate. The full blind test structure is ready for expansion with richer question banks.</p><button onClick={finalTest}>RUN FINAL GATE</button>{feedback&&<div className="success">{feedback}</div>}</div>}</>}
function Settings(){return <><Title title="Settings" sub="Local-only controls. No account or database is required."/><div className="panel"><h2>Create New Identity</h2><p>Paste a new identity-training prompt. The MVP stores the prompt locally for future AI integration.</p><textarea value={profile.prompt||''} onChange={e=>setProfile({...profile,prompt:e.target.value})} placeholder="ENTER NEW IDENTITY PROMPT"/><button onClick={()=>{setS({...s,profile:{...profile}});setFeedback('New identity prompt saved locally. AI generation is intentionally not required in this MVP.')}}>SAVE NEW IDENTITY</button>{feedback&&<div className="success">{feedback}</div>}</div><div className="panel danger"><h2>Reset Training</h2><p>This will erase your local training progress.</p><button className="dangerBtn" onClick={reset}>RESET SYSTEM</button></div></>}
function Locked({title,text}){return <div className="panel lockedBox"><div className="lock">LOCKED</div><h2>{title}</h2><p>{text}</p></div>};function Title({title,sub}){return <div className="title"><div><div className="eyebrow">TRAINING MODULE</div><h2>{title}</h2><p>{sub}</p></div></div>}
return <div className="app"><aside><div className="brand">TE<span>IS</span></div><div className="brandSub">TECH ENTREPRENEUR<br/>IDENTITY SYSTEM</div>{[['dashboard','Dashboard'],['phase1','Phase 1 — Identity Profile'],['phase2','Phase 2 — Integration'],['daily','Daily Training'],['scenarios','Scenario Training'],['memory','Memory Training'],['audit','Identity Audit'],['final','Final Test'],['settings','Settings']].map(([id,n])=><button className={tab===id?'nav active':'nav'} key={id} onClick={()=>setTab(id)}>{n}{id==='phase2'&&!phase1Done&&<em>LOCK</em>}</button>)}<div className="sideProgress"><small>PHASE 1</small><div className="progress"><i style={{width:`${progress}%`}}/></div><b>{progress}%</b></div></aside><main>{render()}</main></div>}
createRoot(document.getElementById('root')).render(<App/>);
